[project]
name = "pydirectus"
version = "0.0.5"
description = "A simple REST API Wrapper for Directus"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests",
]
[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"
